export const areasOfExpertise = [
    "Advertising",
    "Agile",
    "Analytics",
    "B2B",
    "B2C",
    "Big Data",
    "BioTech",
    "Brand Development",
    "Budgeting & Forecasting",
    "Business Development",
    "Business Model Innovation",
    "Communications",
    "Consulting",
    "Content Creation",
    "Cybersecurity",
    "Design",
    "Ecommerce",
    "Electronics",
    "Energy",
    "Engineering",
    "Entrepreneurship",
    "Finance",
    "FoodTech",
    "Fundraising",
    "Healthcare",
    "HR",
    "Innovation",
    "Insurance",
    "InsurTech",
    "Intellectual Property",
    "Investment & Partner Strategy",
    "IoT",
    "IT",
    "Law",
    "Leadership Development",
    "Lean",
    "Legal",
    "M&A",
    "Management",
    "Marketing",
    "Media",
    "Minimal Viable Product (MVP)",
    "Multimedia Production",
    "Negotiations",
    "Operational Excellence",
    "Partnerships & Alliances",
    "Payment",
    "Pitching & Storyboarding",
    "Product Management",
    "Recruitment",
    "RegTech",
    "Regulation/Compliance",
    "Retail",
    "Sales",
    "Smart Mobility",
    "Startup",
    "Strategy",
    "Sustainabilty",
    "Teambuilding",
    "Technology",
    "Telecommunications",
    "Term Sheets",
    "Transportation & Logistics",
    "Venture Strategy & OKRS",
  ];